In [2]:
import gdown

gdown.download('https://bit.ly/3eecMKZ',
               '남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

Downloading...
From: https://bit.ly/3eecMKZ
To: C:\mydata\남산도서관 장서 대출목록 (2021년 04월).csv
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 58.1M/58.1M [00:02<00:00, 20.2MB/s]

'남산도서관 장서 대출목록 (2021년 04월).csv'

In [5]:
with open('남산도서관 장서 대출목록 (2021년 04월).csv') as f:
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

In [9]:
import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode='rb') as f:
    d = f.readline()
print(chardet.detect(d))

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [8]:
pip install chardet

Collecting chardet
  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
Installing collected packages: chardet
Successfully installed chardet-5.2.0
Note: you may need to restart the kernel to use updated packages.

In [11]:
with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR') as f:
    print(f.readline())
    print(f.readline())
    print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","인공지능과 흙","김동훈 지음","민음사","2021","9788937444319","","","","","1","0","2021-03-19",

"2","가짜 행복 권하는 사회","김태형 지음","갈매나무","2021","9791190123969","","","","","1","0","2021-03-19",

In [32]:
import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr')

C:\Users\miso4\AppData\Local\Temp\ipykernel_8140\3829019389.py:2: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr')

In [33]:
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr', low_memory=False) #low memory매개변수를 False로 지정하면 Warning X

In [34]:
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [20]:
df.shape

(401682, 14)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401682 entries, 0 to 401681
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   번호           401682 non-null  int64
 1   도서명          401279 non-null  object
 2   저자           401481 non-null  object
 3   출판사          396887 non-null  object
 4   발행년도         401665 non-null  object
 5   ISBN         401682 non-null  object
 6   세트 ISBN      61871 non-null   object
 7   부가기호         325034 non-null  object
 8   권            68267 non-null   object
 9   주제분류번호       381360 non-null  object
 10  도서권수         401682 non-null  int64
 11  대출건수         401682 non-null  int64
 12  등록일자         401682 non-null  object
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(1), int64(3), object(10)
memory usage: 42.9+ MB

In [23]:
df.describe()

                  번호           도서권수           대출건수  Unnamed: 13
count  401682.000000  401682.000000  401682.000000          0.0
mean   200841.500000       1.127130      10.954300          NaN
std    115955.749751       0.498039      17.836878          NaN
min         1.000000       0.000000       0.000000          NaN
25%    100421.250000       1.000000       1.000000          NaN
50%    200841.500000       1.000000       5.000000          NaN
75%    301261.750000       1.000000      14.000000          NaN
max    401682.000000      40.000000    1468.000000          NaN

In [27]:
sf = pd.read_table('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr') #번외 /tab으로 구분된 파일을 읽는데 사용

In [28]:
sf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401711 entries, 0 to 401710
Data columns (total 1 columns):
 #   Column                                                         Non-Null Count   Dtype
---  ------                                                         --------------   -----
 0   번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,  401711 non-null  object
dtypes: object(1)
memory usage: 3.1+ MB

In [30]:
sf

       번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,
0       1,"인공지능과 흙","김동훈 지음","민음사","2021","97889374443...
1       2,"가짜 행복 권하는 사회","김태형 지음","갈매나무","2021","97911...
2       3,"나도 한 문장 잘 쓰면 바랄 게 없겠네","김선영 지음","블랙피쉬","202...
3       4,"예루살렘 해변","이도 게펜 지음, 임재희 옮김","문학세계사","2021",...
4       5,"김성곤의 중국한시기행 : 장강·황하 편","김성곤 지음","김영사","2021...
...                                                   ...
401706  401678,"韓國現代詩大系","채만묵 編著","한국문화사","1996","9788...
401707  401679,"뉴 웨이브","제임스 모나코 지음","한나래","1996","9788...
401708  401680,"(최인훈 장편소설)화두","최인훈 지음","민음사","1994","9...
401709  401681,"독일 문학과 세계 문학","吳漢鎭 編著","벽호","1995","97...
401710  401682,"참으로 소중한 생각","김일상 지음","동문사","1995","978...

[401711 rows x 1 columns]

In [35]:
df

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401677,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988,NaN,3,811.608,1,0,1970-01-01,NaN
401678,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424,NaN,2,688.04,1,0,1970-01-01,NaN
401679,401680,(최인훈 장편소설)화두,최인훈 지음,민음사,1994,9788937401596,9788937401589,NaN,2,813.6,1,0,1970-01-01,NaN
401680,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405,NaN,3,809.05,2,0,1970-01-01,NaN
401681,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092,0,1,814.6,0,0,1970-01-01,NaN

In [40]:
df = pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='euc-kr',
                 dtype={'ISBN': str, '세트 ISBN': str, '주제분류번호': str})
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [41]:
df.to_csv('ns_202104.csv')

In [50]:
with open('ns_202104.csv', encoding='utf-8') as f:
    for i in range(3):
        print(f.readline(), end='')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [51]:
ns_df = pd.read_csv('ns_202104.csv', low_memory=False)
ns_df.head()

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [53]:
ns_df = pd.read_csv('ns_202104.csv', index_col = 0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [57]:
ns_df = pd.read_csv('ns_202104.csv', index_col=0, low_memory=False)
ss_df = ns_df.head()
ss_df

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
번호,,,,,,,,,,,,,
1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [59]:
ss_df.to_csv('tiger02.csv', index=False) #head()메서드를 통해 가공한 데이터를 csv 파일로 변환